from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.feature_all_of_geometry import FeatureAllOfGeometry
from openapi_server.models.feature_all_of_id import FeatureAllOfId
from openapi_server.models.geo_json_object import GeoJsonObject
from openapi_server import util

from openapi_server.models.feature_all_of_geometry import FeatureAllOfGeometry  # noqa: E501
from openapi_server.models.feature_all_of_id import FeatureAllOfId  # noqa: E501
from openapi_server.models.geo_json_object import GeoJsonObject  # noqa: E501

class Feature(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, bbox=None, geometry=None, properties=None, id=None):  # noqa: E501
        """Feature - a model defined in OpenAPI

        :param type: The type of this Feature.  # noqa: E501
        :type type: str
        :param bbox: The bbox of this Feature.  # noqa: E501
        :type bbox: List[float]
        :param geometry: The geometry of this Feature.  # noqa: E501
        :type geometry: FeatureAllOfGeometry
        :param properties: The properties of this Feature.  # noqa: E501
        :type properties: object
        :param id: The id of this Feature.  # noqa: E501
        :type id: FeatureAllOfId
        """
        self.openapi_types = {
            'type': str,
            'bbox': List[float],
            'geometry': FeatureAllOfGeometry,
            'properties': object,
            'id': FeatureAllOfId
        }

        self.attribute_map = {
            'type': 'type',
            'bbox': 'bbox',
            'geometry': 'geometry',
            'properties': 'properties',
            'id': 'id'
        }

        self._type = type
        self._bbox = bbox
        self._geometry = geometry
        self._properties = properties
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Feature':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feature of this Feature.  # noqa: E501
        :rtype: Feature
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this Feature.


        :return: The type of this Feature.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Feature.


        :param type: The type of this Feature.
        :type type: str
        """
        allowed_values = ["Feature", "FeatureCollection", "Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon", "GeometryCollection"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def bbox(self) -> List[float]:
        """Gets the bbox of this Feature.

        A GeoJSON object MAY have a member named \"bbox\" to include information on the coordinate range for its Geometries, Features, or FeatureCollections. The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries.   # noqa: E501

        :return: The bbox of this Feature.
        :rtype: List[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox: List[float]):
        """Sets the bbox of this Feature.

        A GeoJSON object MAY have a member named \"bbox\" to include information on the coordinate range for its Geometries, Features, or FeatureCollections. The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point. The axes order of a bbox follows the axes order of geometries.   # noqa: E501

        :param bbox: The bbox of this Feature.
        :type bbox: List[float]
        """

        self._bbox = bbox

    @property
    def geometry(self) -> FeatureAllOfGeometry:
        """Gets the geometry of this Feature.


        :return: The geometry of this Feature.
        :rtype: FeatureAllOfGeometry
        """
        return self._geometry

    @geometry.setter
    def geometry(self, geometry: FeatureAllOfGeometry):
        """Sets the geometry of this Feature.


        :param geometry: The geometry of this Feature.
        :type geometry: FeatureAllOfGeometry
        """
        if geometry is None:
            raise ValueError("Invalid value for `geometry`, must not be `None`")  # noqa: E501

        self._geometry = geometry

    @property
    def properties(self) -> object:
        """Gets the properties of this Feature.


        :return: The properties of this Feature.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """Sets the properties of this Feature.


        :param properties: The properties of this Feature.
        :type properties: object
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    @property
    def id(self) -> FeatureAllOfId:
        """Gets the id of this Feature.


        :return: The id of this Feature.
        :rtype: FeatureAllOfId
        """
        return self._id

    @id.setter
    def id(self, id: FeatureAllOfId):
        """Sets the id of this Feature.


        :param id: The id of this Feature.
        :type id: FeatureAllOfId
        """

        self._id = id
