from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.geometry_all_of_coordinates_one_of_inner import GeometryAllOfCoordinatesOneOfInner
from openapi_server import util

from openapi_server.models.geometry_all_of_coordinates_one_of_inner import GeometryAllOfCoordinatesOneOfInner  # noqa: E501

class GeometryAllOfCoordinates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """GeometryAllOfCoordinates - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GeometryAllOfCoordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Geometry_allOf_coordinates of this GeometryAllOfCoordinates.  # noqa: E501
        :rtype: GeometryAllOfCoordinates
        """
        return util.deserialize_model(dikt, cls)
