from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Point(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, x=None, y=None, z=None):  # noqa: E501
        """Point - a model defined in OpenAPI

        :param x: The x of this Point.  # noqa: E501
        :type x: float
        :param y: The y of this Point.  # noqa: E501
        :type y: float
        :param z: The z of this Point.  # noqa: E501
        :type z: float
        """
        self.openapi_types = {
            'x': float,
            'y': float,
            'z': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'z': 'z'
        }

        self._x = x
        self._y = y
        self._z = z

    @classmethod
    def from_dict(cls, dikt) -> 'Point':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Point of this Point.  # noqa: E501
        :rtype: Point
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this Point.

        X coordinate  # noqa: E501

        :return: The x of this Point.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this Point.

        X coordinate  # noqa: E501

        :param x: The x of this Point.
        :type x: float
        """

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this Point.

        Y coordinate  # noqa: E501

        :return: The y of this Point.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this Point.

        Y coordinate  # noqa: E501

        :param y: The y of this Point.
        :type y: float
        """

        self._y = y

    @property
    def z(self) -> float:
        """Gets the z of this Point.

        Z coordinate  # noqa: E501

        :return: The z of this Point.
        :rtype: float
        """
        return self._z

    @z.setter
    def z(self, z: float):
        """Sets the z of this Point.

        Z coordinate  # noqa: E501

        :param z: The z of this Point.
        :type z: float
        """

        self._z = z
