name: macOS-11

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-on-ubuntu:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Build Directory
      run: cmake -E make_directory ${{github.workspace}}/build    
        
    - name: Install Packages
      run: |
            sudo add-apt-repository -y ppa:ubuntugis/ppa
            sudo apt-get -y update -qq
            sudo apt-get install -y gcc-multilib python3 curl zip unzip g++ cmake make -qq
            sudo apt-get install -y --no-install-recommends build-essential ca-certificates  doxygen git libeigen3-dev libgdal-dev libpython3-dev python3-pip python3-matplotlib lcov libgtest-dev libtbb-dev swig python3-pytest -qq
            python -m pip install gcovr

    - name: Configure CMake
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON -DALLOW_PARALLELIZATION=ON -DBUILD_TUTORIALS=OFF -DBUILD_TESTS=ON -DBUILD_DOC=OFF

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(nproc)
      
    - name: Install
      working-directory: ${{github.workspace}}/build
      run: sudo make install
      

    - name: Test C++
      working-directory: ${{github.workspace}}/build
      run: make check
      
    - name: Test Python
      working-directory: ${{github.workspace}}
      run: pytest-3 tests/python/      
